### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by crankynetmaam** [mellowdrifter/python-bgpstuff.net#10]
Once a 1.0.0 or 0.1.0 (okay, maybe 0.0.1 :smile: ) is ready, we should create a package and publish to PyPI.

**Comment by mellowdrifter** [comment]
Was thinking about this too, but I don't really know the process for this. 

If we did go this route, the url should be configurable just in case I start to allow people to spin up their own instances

**Comment by crankynetmaam** [comment]
Very much agree about the configurable URL—I'm glad you brought it up, as I was going to ask you about whether or not spinning up an instance was in your mind somewhere. I would love to be able to do that. I can take a stab at the `setup.py` portion, I just [wrote a post about the whole PyPI process](https://slash64.tech/packaging-a-python-project-with-pypi/) last weekend, so the timing is serendipitous! After the `setup.py` is done, it's pretty easy to cut a release.

**Comment by crankynetmaam** [comment]
Okay, I un-fubared my PR (New one is #14 ), it should be good to go now. New usage with the package structure (if you want to use this as a package) would be `import bgpstuff` and then `client = bgpstuff.Client()`

Essentially the __init__.py file automatically imports `bgpstuff.Client()` when a user performs `import bgpstuff`. Later on, it might be smart to turn `bgpstuff.py` into a module called `client.py` and with the future CLI, that could be `cli.py` etc. Makes imports and the `__init__.py a lot cleaner.

**Comment by mellowdrifter** [comment]
This is done
