### ISSUE TITLE
Implements bogons

### ISSUE THREAD

**Issue by mellowdrifter** [mellowdrifter/python-bgpstuff.net#7]
I have a Go library here - https://github.com/mellowdrifter/bogons/blob/main/bogons.go

Need to re-implement that in Python. But it should be a separate library to import

**Comment by mellowdrifter** [comment]
Initial commit here - https://github.com/mellowdrifter/python-bogons

**Comment by crankynetmaam** [comment]
Should this be a separate library entirely, or a module of the bgpstuff package? (Not really too sure that it matters TBH, I have just been reading a LOT about packages/modules and my head is now spinning thinking of where to use them LOL)

**Comment by mellowdrifter** [comment]
I think separate as it's useful not just for this client. Much like my Go bogons, I import that in at least three separate locations already

**Comment by crankynetmaam** [comment]
Makes sense!

**Comment by mellowdrifter** [comment]
bogons updated. ipaddress.ip_public is returning True for a lot of RFC bogon IPv6 addresses. I'll implement the specific IPv6 RFCs in the client to match my Go code.

IPv4 ispublic does seem to catch all my tests so I'll just use that. However it did return True for multicast addresses so I'm checking for that first

**Comment by crankynetmaam** [comment]
Added [a PR](https://github.com/mellowdrifter/python-bogons/pull/2) to the bogons repo that will help us us to import this easily as a dependency.

**Comment by mellowdrifter** [comment]
This is done
